
version: '3.5'
services:
  site:
    image: webdevops/php-apache:7.4
    volumes:
      - .:/var/www/html
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html
    ports:
      - 8080:80
  composer:
    image: composer
    volumes:
      - ./:/app
    command: composer update
